### ISSUE TITLE
Create Preferences page(s) for Triquetrum and its services

### ISSUE THREAD

**Issue by erwindl0** [eclipse/triquetrum#183]
Several parts of Triquetrum could use an approach to make them configurable. 
E.g. the number of threads reserved for the WorkflowExecutionServiceImpl, maybe the actor library/palette contents for the workflow editor etc.

In Eclipse RCP the standard approach is to provide Preference pages.

**Comment by hugo-bluecorn** [comment]
This is indeed the standard approach for **global** settings which are common for all application such as the file-system location of a specific library. There is an option for changing preferences on a per project basis but doing so should be an exception rather than the norm. Global default values should be common for all projects created and should be set to reasonable defaults **once** by the user and or a priori. Using the preference store is very useful for presenting and setting values when artifacts are created by the IDE such as when a project creation wizard is run or some configuration file is generated.

Given the above. Which are the global preferences neeeded? Can those global preference be categorized into groups of different functionality?

**Comment by erwindl0** [comment]
This is for global settings for a Triquetrum RCP instance, i.e. indeed 
not related to a specific project in one's workspace.

Cfr the 2 examples mentioned in the original issue description :

The workflow execution service now assigns by default a nr of execution 
threads corresponding to the available CPU cores.
This is a valid default choice, but an (advanced) user may want to tune 
that.

The actor library/palette is currently defined through plugin extension 
points.
Users may want to hide/add actors to personalize their palette via 
preferences.

Etc. we can think about more use cases.

**Comment by erwindl0** [comment]
To support #78, I'll start with providing a Preferences page to configure the root location of a file-based WorkflowRepositoryService implementation.

**Comment by cxbrooks** [comment]
Closing this because we have some preferences available now.  A new bug may be opened in the future with specific needs for preferences.
