### ISSUE TITLE
Define and implement a system for dynamic editor palette construction

### ISSUE THREAD

**Issue by erwindl0** [eclipse/triquetrum#189]
To support #18 we need to be able to build the editor's actor palette dynamically, based on external resources, i.o. the current approach that uses Eclipse extensions defined in plugin.xml files.

So we will provide a mechanism & API to define alternative palette content providers.
The idea would be to define this on the level of palette groups and to provide a first implementation that adapts to Ptolemy II's EntityLibrary concept, the org.terraswarm.accessor.AccessorLibrary in particular.

**Comment by erwindl0** [comment]
I've started a trial implementation of an adapter between AccessorLibrary loading and the Triquetrum palette.

It's at https://github.com/erwindl0/triquetrum-capecode

I've added all required deps in my workspace (by hand), i.e. vert.x core + netty + jackson and am able to start-up this extended Triquetrum. But when the AccessorLibrary tries to load the test accessor from the locally contained index.json and BaseA.js, I get an error related to required js files : 

Loading accessor failed: BaseA.js
com.microstar.xml.XmlException: XML element "entity" triggers exception:
  ptolemy.kernel.util.IllegalActionException: Failed to load basicFunctions.js
  in .CapeCode configuration.Accessors.BaseA
Because:
Cannot find file 'ptolemy/actor/lib/jjs/basicFunctions.js' in classpath in platform:/plugin/org.eclipse.triquetrum.ptolemy.capecode.palette/src/main/resources/BaseA.js at line 2 and column 54
Caused by:
 ptolemy.kernel.util.IllegalActionException: Failed to load basicFunctions.js
  in .CapeCode configuration.Accessors.BaseA
Because:
Cannot find file 'ptolemy/actor/lib/jjs/basicFunctions.js' in classpath

So now the problem becomes : being able to load all kinds of js files (and other resources?) from inside a ptolemy bundle?

**Comment by cxbrooks** [comment]
Cool! Thanks for taking a look at this.

Yes, Ptolemy II looks in the classpath to find resources like basicFunctions.js.  I'm not sure how this will work with OSGi.  It is not just the JavaScript actor that looks in the classpath for resources, models can look for resources if the resource starts with $CLASSPATH.  

We had to solve a number of issues surrounding resource loading for WebStart.   See ptolemy/actor/gui/JNLPUtilities.java and nameToFile() and nameToURL() in ptolemy/util/FileUtilities.java

**Comment by erwindl0** [comment]
I've debugged into ptolemy.util.FileUtilities and there's a lot in there that is incompatible with basic OSGi approaches to find resources. 

I need to investigate this in more detail, but a first quick thought is that we may need to change the code in JavaScript and/or FileUtilities to try to be compatible with both standard Ptolemy II/Vergil and with Triquetrum/OSGi. Or in the worst case fork the code in the osgi-2.0 branch from ptII trunk...

**Comment by cxbrooks** [comment]
Right, we will need to figure out how to get resources.  It would probably be best if methods in FileUtilities were modified so that they work with OSGi bundles.   For example ptolemy.actor.lib.jjs.JavaScript has a getResource() method that invokes FileUtilities.nameToURL().  So, if we fix up nameToURL(), we fix this in many places.  The main thing about FileUtilities.java is that it should not depend on OSGi classes at compile or run time.  Thus, any changes to FileUtilities.java that use OSGi classes should use reflection to invoke OSGi-specific methods.

I ran in to similar issues with WebStart, where a .jnlp file lists a series of jar files that can contain resources.  With WebStart, a class could look in the classpath for any resource and the classpath included all the jar files.  This is an old school POJO way of resource lookup, but is probably not compatible with OSGi, where jar files are supposed to be more opaque.   

The reality is that models expect to be able to use $CLASSPATH to get any resource that is in the ptII repo.
