### ISSUE TITLE
UI info in output?

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/triquetrum#72]
I spoke with colleagues at SNL who have been testing Triquetrum. They said that they found UI information in the output file that stores the workflow? I haven't had a chance to look into this, but I'm thinking maybe some of that is showing up in the EMF-generated XML?

**Comment by erwindl0** [comment]
Currently we're using one XMI file to store both the Graphiti Diagram EMF model and the Triquetrum workflow model (linked to each other).
This is the simplest approach to start with, but may not be ideal in the long run.

It is possible to split both models in separate files, which is what I did at the time for Passerelle as well (and there the workflow model was straight Ptolemy II MoML alongside the Graphiti XMI).
Some are in favour of the split approach, but it also has its downside : 2 files for one workflow "ensemble" are more difficult to share/version/keep-in-synch/... than 1 file.

Personally I am in favour to split it up, as my background is more in "headless" runtimes and we could imagine running the workflows without requiring Graphiti dependencies then.
Or even linking it to other graphical representations...

Any ideas/opinions are welcome!

**Comment by erwindl0** [comment]
Another thing : for the ICE integration demo we did for EclipseCon, the demo workflow was exported from Triquetrum into straight Ptolemy MoML XML, which effectively removes the Graphiti elements.

So that's another option we could consider : the editor works in XMI (mixed or split, whatever), and outside of the editor we can still use Ptolemy MoML exports for runtime environments.
(although I don't consider this the best approach myself)

(Ptolemy MoML can also contain limited graphical info like icon types and (x,y) locations of the workflow elements, but it's much more focused on the actual workflow graph than on graphical diagram info.)

And one more thing to keep in mind : Triquetrum has a Java API org.eclipse.triquetrum.workflow.WorkflowRepositoryService that provides some encapsulation on the physical storage method, and returns only the "pure" workflow definition. So if we enforce the usage of that interface when integrating Triquetrum, the actual file format would be less important.

**Comment by cxbrooks** [comment]
I prefer to have one file.

In Triquetrum, awhile back, I believe I noticed that strings like the 
value of a FileParameter were duplicated in the file.  This seems risky, 
so I prefer one file that has a minimal amount of duplicated information 
if possible.

FWIW, The Kepler workflow project uses .kar files which are zip files 
that contain a .moml (Ptolemy Model Markup Language) file and other 
information.  As a code maintainer, I find these files difficult to work 
with when doing operations on the files outside of the tools.  For 
example, sometimes it is necessary to update something in the files or 
clean something up.  In principle, using a  MoML filter to open the 
file, fix the problem and write the file is possible, but sometimes a 
quick and dirty script is much faster.

Another downside of a zip file is that the version control diffs are not 
that useful, though with some tooling it is possible to get meaningful 
information from diffing two .kar files

However, I think model users find the single .kar file to be helpful.  
My interactions with model files is not typical.

So, if we want to have multiple files, it might be nice to bundle them 
in one file, like what the Kepler workflow system does.  Or, I'm 
guessing Eclipse has something similar.

A non-graphical tool should be able to ignore any graphical information 
in the model description file.

For those of you unfamiliar with Ptolemy, ptolemy.moml.MoMLParser is 
used to parse the xml model description.  MoMLParser invokes filters 
that look for certain elements and perform certain operations.  For 
example, ptolemy.moml.filters.RemoveGraphicalClasses does what the name 
suggests.

In principle, using XSLT can do much of what the filters do, but with 
the filters we can inspect the model as it is being parsed.

One key thing to keep in mind is that a MoML file is not a complete 
description of the model because the model instantiates classes, which 
can include actor oriented classes, which are declarations of 
collections of actors that can be instantiated and extended.

_Christopher

On 3/24/16 10:55 AM, erwin de ley wrote:
>
> Currently we're using one XMI file to store both the Graphiti Diagram 
> EMF model and the Triquetrum workflow model (linked to each other).
> This is the simplest approach to start with, but may not be ideal in 
> the long run.
>
> It is possible to split both models in separate files, which is what I 
> did at the time for Passerelle as well (and there the workflow model 
> was straight Ptolemy II MoML alongside the Graphiti XMI).
> Some are in favour of the split approach, but it also has its downside 
> : 2 files for one workflow "ensemble" are more difficult to 
> share/version/keep-in-synch/... than 1 file.
>
> Personally I am in favour to split it up, as my background is more in 
> "headless" runtimes and we could imagine running the workflows without 
> requiring Graphiti dependencies then.
> Or even linking it to other graphical representations...
>
> Any ideas/opinions are welcome!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/eclipse/triquetrum/issues/72#issuecomment-200871993>
>

-- 
Christopher Brooks, PMP                       University of California
Academic Program Manager & Software Engineer  US Mail: 337 Cory Hall
CHESS/iCyPhy/Ptolemy/TerraSwarm               Berkeley, CA 94720-1774
cxh@eecs.berkeley.edu, 707.332.0670           (Office: 545Q Cory)

**Comment by erwindl0** [comment]
No further activity since > 3 months, closing this for now.
